### ISSUE TITLE
Editor errors

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/sales-invoice#107]
Hi,
I don’t know who to write these, so I start with you.

When invoice items are added, header titles are wrong:
![image](https://user-images.githubusercontent.com/22681804/37144471-70fdb2be-22be-11e8-8ad4-3595b252764e.png)

 

So, unit should be quantity and quantity should be unit.

If I add a new invoice for example:
![image](https://user-images.githubusercontent.com/22681804/37144484-7ee1abb0-22be-11e8-955f-bf5635663caa.png)
 

I can’t save it and error does not tell anything specific, so user does not know which label.
And at least IPA can have invoice numbers with ‘ ‘.
When I check overview, this invoice was however saved, and when I open this ‘aa e’ invoice, the label error is given  
![image](https://user-images.githubusercontent.com/22681804/37144506-907101f0-22be-11e8-9e35-3db3f3eea400.png)
 and invoice is not loaded properly. However I didn’t get any other invoices to IPA either (sendingFailed), it was working ok yesterday.

 
![image](https://user-images.githubusercontent.com/22681804/37144520-9843b4d6-22be-11e8-8fab-246fff4a9d79.png)

When I select Create new sales invoice, the new invoice has already invoice lines you had in previous invoice, is it wanted like that? Every other field is empty like they should:
 
![image](https://user-images.githubusercontent.com/22681804/37144536-a04d0e48-22be-11e8-9665-56bc64e5e690.png)

**Comment by nczeranka** [comment]
- translation issue with Quantity/Unit fixed
- missing translations for notification fixed.
- handling of SalesOrderNumbers with special characters improved. Adding rejection of SalesOrderNumbers with characters: "/", "\", "!", ":", ";"
