### ISSUE TITLE
PO lines in the invoice should not be editable

### ISSUE THREAD

**Issue by OKSALTA1** [OpusCapita/sales-invoice#151]
To avoid overcharging the alrady confirmed PO line items should not be editable in the Invoice form.
Exception is if the price field is empty.

Info:
- Price field emtpy: NetPrice == "0.00"
- Editable fields in case of "0.00" price: Quantity, Unit, PriceUnit, NetPrice, Tax

**Comment by nczeranka** [comment]
As soon as a SalesInvoice is created via flip and field netPrice is not empty, then we should disable all the fields which are part of the flip mapping on line item level. This means exceptions are "Custom Clearance No." and "Country of Origin".

![grafik](https://user-images.githubusercontent.com/26661092/44047492-c3037a0c-9f2e-11e8-987a-1ba09bf129f2.png)

Assumption: This is true for possible flip options from other sources in future, too. So we do not have to add an extra status field in SalesInvoiceItem, but simply use existing salesOrderItemNo field (the original item no of the SalesOrder). As long as this field is filled, we assume that the SalesInvoice was created via flipping.

What to do, if the supplier user added required information on the line item?
Proposal: As soon as the user reloads the SalesInvoice, the fields are blocked, too. Same behaviour as if he has done a PO-Flip on Sales-Invoice service.
