### ISSUE TITLE
Invoice UI enhancements

### ISSUE THREAD

**Issue by OKSALTA1** [OpusCapita/sales-invoice#154]
Customer VAT:ID to the invoice
EDI ID explanation in front or the number

**Comment by nczeranka** [comment]
![grafik](https://user-images.githubusercontent.com/26661092/44102920-29f708ac-9feb-11e8-8283-dd0f55b2cdc7.png)

Customer VAT Id was added to the ui. Please check (on dev) for
- position
- translations - I reused the vat-id label, but added now own labels for supplier and customer vat id

Additionally please explain the requirement: "EDI ID explanation in front or the number".

**Comment by nczeranka** [comment]
As discussed with PM, we will no longer show the ediId, though it has no relevance for the customers.
