### ISSUE TITLE
Generate ISR/ESR based payment reference into invoice for switzerland domestic case

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/sales-invoice#177]
We need to generate a 27 digit bankPaymentReference,
the so called ISR/ESR code

This has several conditions:
* Creditor (Supplier) is located in Switzerland
* Creditor (Supplier) selected a bank account that has ISR/ESR participant number filled
* Debtor (Customer) is located in Switzerland
* Creditor (Supplier) has filled in a invoice number

https://www.raiffeisen.ch/rch/de/firmenkunden/liquiditaet-und-zahlungsverkehr/debitoren/oranger-einzahlungsschein.html

https://advendio.atlassian.net/wiki/spaces/SO/pages/130195958/6.1.9+Generate+Swiss+ISR+Code+ESR+Code

It seems that we need to create a fakturanr which is the invoice number + customer number and llimited to 20 digits.
If we dont find a rule for this, we can't generate the ref no

**Comment by nczeranka** [comment]
Moved to BNP-51
