### ISSUE TITLE
New explenation to Zero Vat %

### ISSUE THREAD

**Issue by OKSALTA1** [OpusCapita/sales-invoice#184]
When zero Vat % is used the help/warning text should be changed to
- en: “The VAT rate is 0%. Please include the legal basis for the use of 0% VAT.”
- de: "Bitte hinterlegen Sie die gesetzlichen Grundlagen für die Verwendung der MwSt. von 0%."

**Comment by nczeranka** [comment]
Implemented
Published to dev and stage.
