### ISSUE TITLE
Bank Payment reference validation in Key In form

### ISSUE THREAD

**Issue by OKSALTA1** [OpusCapita/sales-invoice#201]
The Bank payment reference field needs validations based on the Suppliers county specific requirements. If the validation fails there should be a notification/warning but the invoice should still be possible to send.  

Validations should be included if the Supplier is issuing a Bank Payment Reference and is from:
-	Finland, then the reference validation should be done according to Finnish reference number validation rules http://www.finanssiala.fi/maksujenvalitys/dokumentit/Forming_a_Finnish_reference_number.pdf
Length 4-20, Check digit Weight 137

-	Sweden, Then the validation should be done according to Swedish OCR reference (chapter 5.2.2 Calculate check digit using modulus10) https://www.bankgirot.se/globalassets/dokument/anvandarmanualer/bankgiroreceivables_bankgiroinbetalningar_usermanaual_en.pdf
Length 2-25, Check digit modulus 10 / Luhn10 (see https://en.wikipedia.org/wiki/Luhn_algorithm) + Length check

Cash Management has validation rules script (C Sharp ValidationRules.xml) if that would be helpful?

**Comment by nczeranka** [comment]
For online validation see:
https://www.bankgirot.se/en/services/incoming-payments/bankgiro-receivables/ocr-reference-control/

**Comment by nczeranka** [comment]
Installed on stage.
