### ISSUE TITLE
Finnish translations in Key in form

### ISSUE THREAD

**Issue by OKSALTA1** [OpusCapita/sales-invoice#202]
In the Key In form couple of texts still needs to be translated into Finnish.

English term Bank Payment Reference should be "Maksuviite" in Finnish.

Viitenumero should be changed to "Ostajan viite"

Add Surcharges should be changed to "Lisäkulut"
Under surcharges the types:
- Freights - Rahti
- Packaging - Pakkaus
- Postage - Postitus

Invoice PDF header:
English term Bank Payment Reference should be "Maksuviite" in Finnish.
Viitetieto should be changed to "Ostajan viite"

**Comment by nczeranka** [comment]
Already available, except of:
> Add Surcharges should be changed to "Lisäkulut"

which is *Lisää lisäkulu*. What is correct?

**Comment by OKSALTA1** [comment]
Thats correct. Was discussed with Tore already before.
