### ISSUE TITLE
Item name to be mandatory

### ISSUE THREAD

**Issue by OKSALTA1** [OpusCapita/sales-invoice#220]
Item/Name is a mandatory field if line element exist. 
Without that xml will not pass schema validation.

**Comment by nczeranka** [comment]
But item name is usually not required in SAP.

I believe that we 
-	either need a customer specific configuration or
-	adjust the Sirius mapping in the way that empty names are filled from the ProductId.

I would prefer the latter one, though it means less work for all of us (and no restriction for other customers/suppliers)

**Comment by nczeranka** [comment]
No feedback in the last 6 months. Assumption is that it was solved on Sirius side (see comment above).
