### ISSUE TITLE
Manual Mapping - only on second click

### ISSUE THREAD

**Issue by nczeranka** [OpusCapita/sales-invoice#43]
After selecting a form element, you need two clicks to select text from the pdf. The first click is not used.

**Comment by amonliza** [comment]
This happens in firefox. In chrome selecting works fine.

**Comment by nczeranka** [comment]
We can reproduce the described problems on Chrome, too:
- open https://develop.businessnetwork.opuscapita.com/sales-invoice/create/4711/SWE_00065_1.pdf
- click in field "Order Number" -> field is activated (blue frame)
- click and drag in the pdf view -> nothing happens except that the blue frame is removed.
- click and drag again -> marked text is moved to the previously markd entry field.

On Firefox we had a slightly different behaviour:
- open https://develop.businessnetwork.opuscapita.com/sales-invoice/create/4711/SWE_00065_1.pdf
- click in field "Order Number" -> field is activated (blue frame)
- click and drag in the pdf view -> text from the beginning of the pdf page is marked and copied. Start position when clicking is not taken into account.
- click and drag again -> marked text is moved to the previously markd entry field.

**Comment by amonliza** [comment]
Could be reproduced in chrome 62. In 56 was working correctly. Reason found. Correction in progress.
