### ISSUE TITLE
Common access of Invoice Address

### ISSUE THREAD

**Issue by nczeranka** [OpusCapita/sales-invoice#61]
Currently we have to implement fetching the right address in each occurrency. Here for the sales-invoice:
- Supplier -> Addresses['default'][0]
- Customer -> Addresses['invoice'][0] || Addresses['default'][0]

The same apporach is implemented on client side for ui and on server side for PDF generation.

Most probably other applications have the same problem. So why not provide common endpoints in supplier and customer? E.g.:
- /api/suppliers/:supplierId/addresses/:type[/default]
- /api/customer/:customerId/addresses/:type[/default]

Whatever default means. Possibly we should add a "default" flag in the addresses that defines which address to use if multiple of a type are defined. (Or we should not allow to define more than one address of one type)

**Comment by nczeranka** [comment]
What do you think about this proposal? If approved, I can create tickets for supplier and customer

**Comment by lasong** [comment]
This endpoint will conflict the endpoint for getting a supplierAddress by id. What we can do is extending the addresses endpoint to be able to query type. So something like:

```
/api/suppliers/:supplierId/addresses?type=[type]
/api/customer/:customerId/addresses?type=[type]
```

As for type handling/validation, I would not do this till it becomes a business requirement. At the moment it's not..
